matrix:
  include:
    - os: linux
      dist: trusty
      language: cpp
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -q
        - sudo apt-get install -y g++-7
        - export CXX=/usr/bin/g++-7
      script:
        - cmake .
        - cmake --build .
        - ./night tests/test.night
    - os: windows
      language: cpp
      script:
        - cmake -G "MinGW Makefiles" .
        - cmake --build .
        - night ../tests/test.night

before_install:
    - eval "${MATRIX_EVAL}"