matrix:
  include:
    - os: linux
      dist: trusty
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      script:
        - export CXX=g++-7
        - cmake .

before_install:
    - eval "${MATRIX_EVAL}"