version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Compiling Code
          command: 'g++ -std=c++17 -Wall -Werror -o night src/night.cpp'
      - run:
          name: Testing Code
          command: './night tests/test.night'
