version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Installing g++
          command: 'choco install mingw'
      - run:
          name: Compiling Code
          command: 'g++ -std=c++17 -Wall -Werror -o night src/night.cpp'
      - run:
          name: Testing Code
          command: './night tests/test.night'
  test:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Compiling Code
          command: 'g++ -std=c++17 -Wall -Werror -o night src/night.cpp'
      - run:
          name: Testing Code
          command: './night tests/test.night'

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
