version: 2.1
jobs:
  one:
    steps:
      - checkout
      - run: g++ -std=c++17 -o night src/night.cpp
  two:
    steps:
      - run: echo "testing"
      
workflows:
  version: 2.1
  one-and-two:
    jobs:
      - one
      - two
