version: 2.1

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
        name: installing GCC
        command: 'apt-get update && apt-get install -y gcc g++'
      - run:
        name: compiling
        command: 'g++ -std=c++17 src/night.cpp'