version: 2.1
jobs:
  linux-build:
    steps:
      - checkout
      - run: g++ -std=c++17 -o night src/night.cpp
  two:
    steps:
      - run: echo "testing"
      
workflows:
  version: 2.1
  build:
    jobs:
      - linux-build
      - two
